"""soft_delete_created_at_updated_at

Revision ID: 89a909e8dcae
Revises: 74a5762a3ecc
Create Date: 2026-02-05 14:18:04.481297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "89a909e8dcae"
down_revision: Union[str, Sequence[str], None] = "74a5762a3ecc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column(
            "created_at",
            sa.String(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "categories",
        sa.Column(
            "updated_at",
            sa.String(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column("categories", sa.Column("deleted_at", sa.String(), nullable=True))
    op.add_column(
        "product_inventory",
        sa.Column(
            "created_at",
            sa.String(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "product_inventory",
        sa.Column(
            "updated_at",
            sa.String(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "product_inventory", sa.Column("deleted_at", sa.String(), nullable=True)
    )
    op.add_column(
        "product_prices",
        sa.Column(
            "created_at",
            sa.String(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "product_prices",
        sa.Column(
            "updated_at",
            sa.String(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column("product_prices", sa.Column("deleted_at", sa.String(), nullable=True))
    op.add_column(
        "products",
        sa.Column(
            "updated_at",
            sa.String(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column("products", sa.Column("deleted_at", sa.String(), nullable=True))
    op.alter_column(
        "products",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.add_column(
        "ratings",
        sa.Column(
            "created_at",
            sa.String(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "ratings",
        sa.Column(
            "updated_at",
            sa.String(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column("ratings", sa.Column("deleted_at", sa.String(), nullable=True))
    op.add_column(
        "reviews_summary",
        sa.Column(
            "created_at",
            sa.String(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "reviews_summary",
        sa.Column(
            "updated_at",
            sa.String(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
    )
    op.add_column(
        "reviews_summary", sa.Column("deleted_at", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews_summary", "deleted_at")
    op.drop_column("reviews_summary", "updated_at")
    op.drop_column("reviews_summary", "created_at")
    op.drop_column("ratings", "deleted_at")
    op.drop_column("ratings", "updated_at")
    op.drop_column("ratings", "created_at")
    op.alter_column(
        "products",
        "created_at",
        existing_type=sa.String(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_column("products", "deleted_at")
    op.drop_column("products", "updated_at")
    op.drop_column("product_prices", "deleted_at")
    op.drop_column("product_prices", "updated_at")
    op.drop_column("product_prices", "created_at")
    op.drop_column("product_inventory", "deleted_at")
    op.drop_column("product_inventory", "updated_at")
    op.drop_column("product_inventory", "created_at")
    op.drop_column("categories", "deleted_at")
    op.drop_column("categories", "updated_at")
    op.drop_column("categories", "created_at")
    # ### end Alembic commands ###
