# Use an official lightweight Python image
FROM python:3.10-slim

# Set working directory inside container
WORKDIR /app

# Copy rest of the project
COPY . .

# Run your application
CMD ["python", "test_app/main.py"]